### ISSUE TITLE
Several issues

### ISSUE THREAD

**Issue by ItsPhenom** [EvoTM/EvoSC#11]
- [ ] kick/ban buttons visible for players w/o permissions
- [ ] playerlist dialog opens in unwanted areas (e.g. under cp times), playear leave resets it
- [ ] music dialog opens under other dialogs
- [x] side panel font too small on bigger(?) screens
- [x] /gear does nothing
- [x] 50% chance if /pm is working (login / ingame nick)
- [x] bleeding on some fonts

References:
![1SQ7Bkv](https://user-images.githubusercontent.com/4627720/59320232-e7674580-8ccd-11e9-85eb-f111276033df.png)
![](https://i.imgur.com/CNh5ul7.png)
![FVFoNOz](https://user-images.githubusercontent.com/4627720/59320258-fe0d9c80-8ccd-11e9-825d-b0d9a6751f8e.png)

**Comment by brakerb** [comment]
Fixed gear in 0.69.2 (/)
