### ISSUE TITLE
Directory based map selection

### ISSUE THREAD

**Issue by kdankert** [EvoTM/EvoSC#115]
**Describe the feature you'd like to see in EvoSC**
It would be cool, if I could select all maps in a subdirectory of the MAPS directory as being part of a match settings profile. Right now I am doing this with a script and editing match settings manually. I don't think that this would cause any read issues in the filesystem, as Maps from subdirectories can already be selected one by one. It would be a call feature for admins if they host a tournament or switching between different playlists of maps.

**Comment by kdankert** [comment]
I am currently working on this, just to make sure we aren't doing the same work on this issue. Should I continue trying to implement this?

**Comment by brakerb** [comment]
@kdankert Hey, I am currently not working on it. You can give it a try

**Comment by kdankert** [comment]
This could be closed now, as this feature was implemented
