### ISSUE TITLE
/pm command has no usage explanation

### ISSUE THREAD

**Issue by snixtho** [EvoTM/EvoSC#120]
**Describe the bug**
Well not exactly a bug per se, but a description for the `pm` command is missing in the help window. People often ask if there is a way to send private messages to people, and the fact that the help window doesn't even describe how to use this feature doesn't help at all with this.

**Expected behavior**
I suggest adding a small description and even an example for how to use it. Just writing `/pm` in the chat doesn't provide any useful usage information either and an idea could be to output an explanation for how to use the command there as well.

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/3867739/111904474-7975b380-8a47-11eb-8beb-70d3faca423c.png)

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.99.11

**Comment by brakerb** [comment]
Added in latest commit
