### ISSUE TITLE
No local-record registrations for some players when disabling registration during warmup

### ISSUE THREAD

**Issue by snixtho** [EvoTM/EvoSC#122]
**Describe the bug**
When enabling no local records during warmup, some players wont have records registered at all during the live round. It doesn't happen often, and I'm not entirely sure what causes it. This is a very big problem during cups when it is important for people to have their times registered for a fair ranking.

**Expected behavior**
Local records should always be registered during the live round.

**To Reproduce**
It's hard to reproduce. Don't know if it occurs due to faulty connections or some other bugs. But you can set `ignore-warmup-times` to `true` in `locals.config.json` and some times local records wont register.

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.99.11

**Comment by brakerb** [comment]
fixed
