### ISSUE TITLE
Track name colors not properly parsed in message "upcoming map XXX"

### ISSUE THREAD

**Issue by janmarques** [EvoTM/EvoSC#124]
**Describe the bug**
See screenshot. The track name is "Four Seasons" (with fancy colors on each of the letters), but seemingly the color code is being displayed instead of parsed and applied.

**Screenshots/Logs**
If any available, add screenshots/logs to help explain your problem.
![image](https://user-images.githubusercontent.com/27282861/112726783-84d14f00-8f1f-11eb-8d10-8e43ba279216.png)

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.99.13

**Comment by brakerb** [comment]
The regex was case sensitive, I accidently removed the i-flag. I readded it in the latest commit.
Should work again now.
