### ISSUE TITLE
Current map is not set. Exiting...

### ISSUE THREAD

**Issue by Chris92de** [EvoTM/EvoSC#13]
Hello, I tried setting up evoSC, however I'm encountering the following issue.
When I join the server or after a certain amount of time, evoSC will spit this error:

`esc\Classes\Log::error(...): Current map is not set. Exiting...`
Attached is the log file, which seemingly changes the file name for the first map several times?
[2019-06-13.txt](https://github.com/EvoTM/EvoSC/files/3287742/2019-06-13.txt)

**Comment by hpD-orso** [comment]
I've had this problem since the beginning, too. i have to skip the actual map and after skip i can start the controler :-} my workaround

**Comment by Chris92de** [comment]
Okay, found the issue.
It's due to the controller thinking there's only one map if the <ident> field isn't filled out in the MatchSettings file.

**Comment by brakerb** [comment]
Is it that there is no map specified in the match-settings or is there an empty <map></map> entry thats causing it?

**Comment by Chris92de** [comment]
Basically, maps with an empty ident entry will cause issues, due to the MapController (when it first loads all maps on start of ESC) thinking there's several entries of the same map and just updating the file name for it.

**Comment by Chris92de** [comment]
Should be fixed with https://github.com/EvoTM/EvoSC/commit/9079c3f452744f481c5535892827571eb3acfb4f
