### ISSUE TITLE
/target does not work, and does it show up in / help

### ISSUE THREAD

**Issue by KennyBz** [EvoTM/EvoSC#142]
On EvoSC Develop 99.22, /target does not work, and does it show up in / help

![image](https://user-images.githubusercontent.com/15847867/117468498-08398380-af55-11eb-9267-902d5cb2385c.png)

Edit: Times no longer displayed below the car either / Neither the + and -

![image](https://user-images.githubusercontent.com/15847867/117479332-7fc0e000-af60-11eb-94ab-737de2357df6.png)

**Comment by brakerb** [comment]
Is it possible, that you have disabled the module because of the error popup?

**Comment by KennyBz** [comment]
No I just looked by doing an update on another server in the latest develop version but the result is the same.

And of course I looked to see if it was deactivate and not it is indeed activated!

**Comment by snixtho** [comment]
I just checked on the latest version, the command is there. And also displayed in /help and the times are displayed:

![image](https://user-images.githubusercontent.com/3867739/117585351-492ac700-b112-11eb-9b31-5bc6d7737e26.png)
![image](https://user-images.githubusercontent.com/3867739/117585362-5f388780-b112-11eb-917a-dd7295046ad7.png)
![image](https://user-images.githubusercontent.com/3867739/117585402-9149e980-b112-11eb-82ae-f15db4622d9c.png)

So I'm not really sure what you are doing. Make sure the module `CpDiffs` is enabled.

**Comment by KennyBz** [comment]
Im on TM² not on TM2020
