### ISSUE TITLE
//settings not work

### ISSUE THREAD

**Issue by KennyBz** [EvoTM/EvoSC#176]
On TM2020 and TM² the //settings commands does not work but it does not say that the command does not exist just it does not show

(Whether on the latest master or develop version it does not work)

**Comment by snixtho** [comment]
Please use this template when reporting bugs:
![image](https://user-images.githubusercontent.com/3867739/122560468-eeee2180-d040-11eb-95bc-c430a89834ab.png)

**Comment by brakerb** [comment]
Please use the issue template and give us more detailed informations about your setup.
