### ISSUE TITLE
/rank command not live

### ISSUE THREAD

**Issue by layland34** [EvoTM/EvoSC#248]
**Describe the bug**
Was playing on Evo Dirt Server in TM2020. Types /rank to see my global server rank. This rank keeps frozen the whole time I am on the server. Between maps the message "Your server rank is ..." keeps updating correctly. The response from /rank is always the rank from when you joined the server.

**Expected behavior**
Typing /rank showing you your current serverrank. 

**To Reproduce**
Join server play a inplayed maps, compare serverrank.

**Screenshots/Logs**
If any available, add screenshots/logs to help explain your problem.

**EvoSC (please complete the following information):**
 - EvoSC-Version: [e.g. 0.87.x] (get with `php esc version`)
 - Game: TM2020

**Comment by Chris92de** [comment]
Thanks for the report, I'll look into it!

**Comment by brakerb** [comment]
Fixed in latest develop
