### ISSUE TITLE
Next map won't be displayed and position is wrong

### ISSUE THREAD

**Issue by keplusplus** [EvoTM/EvoSC#25]
And I found another thing that doesn't work properly.

When the GUI is visible, I get this in the center of the screen: https://i.imgur.com/CcoGylF.png

The current map name and author is not shown correctly and the position is not correct. I use the default settings (next-map on the right slot 4). I tried also on the right slot 3.

I'm very new to your nice server controller and maybe I've done a mistake. I really appreciate your work :D

**Comment by ItsPhenom** [comment]
Try the develop branch, the current map widget got fixed some time ago and the changes are not merged into the master branch yet.

**Comment by LeGmask** [comment]
It is because you add the map without mx. if you use mx there arn't bug but if you add with Adminserv it bug everytime and the map don't appeare in map list !

**Comment by keplusplus** [comment]
I can't confirm that, in the develop branch it works fine, even with non-MX maps. Position and name / author is correct.

**Comment by LeGmask** [comment]
In the master branch, but not the latest version, it was that

**Comment by brakerb** [comment]
master-branch should now have a somewhat stable version. Adding maps from MX didnt work, if the MX-dir was missing, that was fixed.
If you add a map with adminserv, you need to restart evosc. Adding maps with adminsserv is not yet supported, but will be in the future.

**Comment by LeGmask** [comment]
Ok good job !
