### ISSUE TITLE
Error message with evosc master on tm2020

### ISSUE THREAD

**Issue by KennyBz** [EvoTM/EvoSC#253]
**Describe the bug**
I followed this tutoral (https://wiki.evotm.com/books/evosc-users-guide/page/download-installation) without do nothing wrong and i go an error (see picture)
I use this php version on ubuntu 18.04:
**PHP 7.4.29 (cli) (built: Apr 21 2022 10:16:17) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.29, Copyright (c), by Zend Technologies**

And i follow this tutorial for my server:
https://wiki.trackmania.io/en/dedicated-server/Setup/Windows

**To Reproduce**
Just follow this tuto:
https://wiki.evotm.com/books/evosc-users-guide/page/download-installation

**Screenshots/Logs**
If any available, add screenshots/logs to help explain your problem.

**EvoSC (please complete the following information):**
 - EvoSC-Version: [0.99.70]
 - Game: TM2020

**When using git (please complete the following information):**
 - Current-Commit: [624d1ed24ef13a33ce81db943c9e9d1cd6c6405e]

![unknown](https://user-images.githubusercontent.com/15847867/171070968-fbc4678d-5d17-4bd2-836b-b12b0ef0b142.png)

**Comment by Chris92de** [comment]
fixed in develop branch
