### ISSUE TITLE
Migration error: "maps" table got renamed to "pbs" during the migration process

### ISSUE THREAD

**Issue by keplusplus** [EvoTM/EvoSC#26]
I hope I'm not annoying you, but when I migrate the tables to the empty database with "php esc migrate" (develop branch), the "maps" table will be generated, but when I try to run the service, the program of can't find the maps table and I gets removed from the database. This seems to be a bug.

Addition: I think the table gets dropped by the 1568455055_remove-mx-details-from-maps-table.php file.

**Comment by brakerb** [comment]
Yes this is a bug, I will look when I am back home and fix it. Thank you for submitting it.

**Comment by brakerb** [comment]
@keplusplus Delete all tables, pull the latest update with `git pull` and run EvoSC with `php esc run`. Go through the setup and it should start afterwards. Make sure you set default match-settings.
Please comment here if it works or not :)

**Comment by brakerb** [comment]
Fixed in https://github.com/EvoTM/EvoSC/commit/bde1bec2afd28e7ac97070a314d0e40366b648e6
