### ISSUE TITLE
Warm Up interface isn't here

### ISSUE THREAD

**Issue by LeGmask** [EvoTM/EvoSC#27]
Hey,
With the new update when I use a warm up the interface appears but goes down out of the screen.
It is a bug or bad setup ?
Ty
Gmask

**Comment by brakerb** [comment]
Hey, rounds mode is not fully supported yet so probably a bug.

LeGmask <notifications@github.com> schrieb am Fr., 4. Okt. 2019, 18:35:

**Comment by LeGmask** [comment]
ok reported so !

**Comment by brakerb** [comment]
Warum-Up widget is now enabled in rounds mode.
