### ISSUE TITLE
Z-Index broken on some elements after latest TM update (2022-09-08)

### ISSUE THREAD

**Issue by Chris92de** [EvoTM/EvoSC#273]
**Describe the bug**
Some Z-Index issues

**Expected behavior**
No Z-Index issues

**To Reproduce**
1. Go to Group Manager
2. Click on Add Player/Members of an existing group
3. Try to add a player to the group
4. Whole column will be highlighted and the Add/Remove buttons won't be clickable

1b. Go to Match Setting Manager
2b. Edit a Matchsetting
3b. Try to edit any of the values
4b. No value columns are editable

**Screenshots/Logs**
![image](https://user-images.githubusercontent.com/5523125/189504598-0da78121-fc7f-4abc-9bca-c8ab6503d8af.png)
![image](https://user-images.githubusercontent.com/5523125/189504624-0d6493f1-856a-4fcd-804f-65a0e081e11d.png)

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.99.87
 - Game: TM2020

**Comment by brakerb** [comment]
af1508235a67d40db7c3ad4575db5eb477376f83

Should fix those issues

**Comment by Chris92de** [comment]
This seems to be fixed, thanks!
