### ISSUE TITLE
Logfiles goes crazy up to 30GB !! 30 Gigabytes LOGFILE !!

### ISSUE THREAD

**Issue by BestNoob** [EvoTM/EvoSC#31]
I didnt got EvoSC to work with PHP7.3 so i tried it with the older PHP5.6 and it seems to work, but after 1 Day the Logfile grows up to 30GB 😄 and the server crashed.

(Windows Server x64)

And it also brings Maniaplanet to create a 30GB+ Logfile ....

**Comment by brakerb** [comment]
The controller can't run on php5, it uses functionality only 7+ has. And if you expect help, please provide information like the first lines of the log, we can't fix bugs by guessing.

**Comment by BestNoob** [comment]
> 
> 
> The controller can't run on php5, it uses functionality only 7+ has. And if you expect help, please provide information like the first lines of the log, we can't fix bugs by guessing.

How should i open a 30GB logfile ? .... without a supercomputer
