### ISSUE TITLE
Clicking on the maps tab in the Matchsettings Editor leads to an Compilation Error

### ISSUE THREAD

**Issue by Vipale** [EvoTM/EvoSC#40]
![evosc3](https://user-images.githubusercontent.com/59482086/81582720-a4679380-93b0-11ea-9553-44549c69ab8a.jpg)
![evosc4](https://user-images.githubusercontent.com/59482086/81582724-a6315700-93b0-11ea-9493-e2ddf03e3b9a.jpg)

EvoSC-Version: 0.83.x
Branch: master 
Current-Commit: 9f18692d67178bcfef309d14c34ea7f7381436b8

**Comment by brakerb** [comment]
The problem does not happen in the current version (develop) anymore. But the map-selection itself needs to be updated. It will work again with the next merge from develop to master.
