### ISSUE TITLE
Local Track Karma

### ISSUE THREAD

**Issue by Vipale** [EvoTM/EvoSC#41]
I would be nice to have local track karma displayed somewhere. 
So you can drop maps according to the players taste.
I guess best place to add would be next to the global karma on the maps overview.

![evosc5](https://user-images.githubusercontent.com/59482086/81583338-84849f80-93b1-11ea-9ad1-b2cd70dcdf13.jpg)

**Comment by brakerb** [comment]
Map list and widget now display local track karma. In the future there might be the possibility to view both.
Karma is still gong to be send to MX/TMX, just now it is disabled till the API works correctly (all Karma will be send afterwards when it is online again).
