### ISSUE TITLE
Limit lines for CP Tracking

### ISSUE THREAD

**Issue by Chicane90** [EvoTM/EvoSC#43]
Would be nice if chose cp trackers are limited to, lets say 5 rows, and if there starts a sixth row
it becomes scrollable/expandable, with only 5 lines showing
not a big issue on this map, but if we got to a map wich 60+ checkpoints (not so common, but these still exists, it becomes a bit "bulky"
![image](https://user-images.githubusercontent.com/23026126/85202830-73f90a80-b309-11ea-806b-c8bc5ae05cc2.png)
Just a nice to have (and only important for RPG Stuff :) )

**Comment by brakerb** [comment]
https://i.imgur.com/KsRHU3p.gif
