### ISSUE TITLE
/replay asks for 0 mins by default

### ISSUE THREAD

**Issue by snixtho** [EvoTM/EvoSC#44]
**Describe the bug**
Go the evo advanced server and type /replay without any arguments, it will ask for 0 minutes.

**Expected behavior**
Should ask for 5 minutes.

**To Reproduce**
1. Go to evo advanced.
2. Type `/replay`

**Screenshots/Logs**
If any available, add screenshots/logs to help explain your problem.

**EvoSC (please complete the following information):**
 - EvoSC-Version: [e.g. 0.87.x] (get with `php esc version`)

**When using git (please complete the following information):**
 - Current-Commit: [e.g. bb3eefb3622e864ad480641f281d4a2e4be50a69] (get with `git rev-parse HEAD`)

**Comment by brakerb** [comment]
fixed
