### ISSUE TITLE
cant not start

### ISSUE THREAD

**Issue by Syinea** [EvoTM/EvoSC#50]
The template ID for 'C:\TM2020\XXXX\EvoSC\EvoSC\core\Modules\ASay\Templates\window.latte.xml' could not be det
  ected. Please check that your naming is correct.

any solutions?

**Comment by brakerb** [comment]
EvoSC isn't fully tested on windows yet. 
I made several improvements lately, I have merged them into master. Pull the latest changes and see if it works.

Before 1.0 EvoSC will be made fully compatible. Until then I can recommend using a linux-distribution. Running it in WSL is also possible.

**Comment by brakerb** [comment]
Duplicate https://github.com/EvoTM/EvoSC/issues/56
