### ISSUE TITLE
Not hightlighting/focusing Local or Dedi positions

### ISSUE THREAD

**Issue by Reactor-UK** [EvoTM/EvoSC#53]
**Describe the bug**
Not focusing or hightlighting local or dedi positions if position is outside of top 3. (Note: Displays correctly when selecting full local or dedi list)

**Expected behavior**
Should focus and highlight local and/or dedi position on side lists

**To Reproduce**
N/A

**Screenshots/Logs**
N/A

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.91.0

**When using git (please complete the following information):**
N/A

**Comment by brakerb** [comment]
Can you please check with the latest version of develop-Branch if the problem still exists?

**Comment by Reactor-UK** [comment]
braker, I would however, you're hosting so I don't have access to update (to the best of my knowledge)

**Comment by brakerb** [comment]
fixed
