### ISSUE TITLE
[Suggestion] Button to send message through server API?

### ISSUE THREAD

**Issue by mantazzo** [EvoTM/EvoSC#59]
I don't know how to name it proper.
Basically, with TM2020 (as I like to call it), when you play on the server with a Starter Access account, you are not allowed to chat (which, IMO, is a stupid restriction, but eh, NADEO knows better I suppose). As servers can be hosted on LAN too (with the server controllers working too) I played a few games with my friends and the restriction to chat is, frankly, quite annoying - we would like to taunt each other to do better!
What I'm trying to suggest - could you maybe make an additional button in the scoreboard (for example) which, after you press it, could open a window where you could send a (limited length) message (maybe also rate-limit too?), if it's not too difficult? Probably the same way as server now sends messages in the chat for any new/updated records, but with the user who wants to send a message, and message's content... If you understand what I'm trying to say.
I understand if you don't see the reason why this would be needed, but it would be a nice small feature to have.

**Comment by snixtho** [comment]
Not sure if this is something we would implement officially, but I think it could be a good idea for an user-created module.

**Comment by nouseforname** [comment]
This feature won't be added officially, as it is not supposed to be used:
[Click here](https://openplanet.nl/next/club)
