### ISSUE TITLE
Ingame Message Manager not saving

### ISSUE THREAD

**Issue by Sil3ntStorm** [EvoTM/EvoSC#60]
I realize it says that you're only accepting bug reports for the master branch, and this is happening on develop. If you would rather not have them, feel free to let me know in the comments and I will not be reporting any further issues on develop, even though I feel like issues there should be noted somewhere as well.

**Describe the bug**
Scheduled message saving / adding from within the ingame UI is not working. Hitting Add doesn't close the window and doesn't save the message.

**Expected behavior**
The new message should have been saved and the window should disappear.

**To Reproduce**
Use `//messages` click add and fill out the fields, hit save.

**Screenshots/Logs**
```
EscRun->execute(): EvoSC encountered an error: Argument 2 passed to EvoSC\Modules\InfoMessages\InfoMessages::update() must be an instance of Illuminate\Support\Collection, instance of stdClass given
EscRun->execute(): #0 [internal function]: EvoSC\Modules\InfoMessages\InfoMessages::update()
#1 EvoSC/core/Classes/ManiaLinkEvent.php(174): call_user_func_array()
#2 EvoSC/core/Controllers/EventController.php(262): EvoSC\Classes\ManiaLinkEvent::call()
#3 EvoSC/core/Controllers/EventController.php(78): EvoSC\Controllers\EventController::mpPlayerManialinkPageAnswer()
#4 EvoSC/core/Commands/EscRun.php(222): EvoSC\Controllers\EventController::handleCallbacks()
#5 EvoSC/vendor/symfony/console/Command/Command.php(255): EvoSC\Commands\EscRun->execute()
#6 EvoSC/vendor/symfony/console/Application.php(1000): Symfony\Component\Console\Command\Command->run()
#7 EvoSC/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Application->doRunCommand()
#8 EvoSC/vendor/symfony/console/Application.php(147): Symfony\Component\Console\Application->doRun()
#9 EvoSC/esc(63): Symfony\Component\Console\Application->run()
#10 {main}
```
**EvoSC (please complete the following information):**
0.9.14

**When using git (please complete the following information):**
d2500183109ec9d0eeec97beb65efec779899d3d

**Comment by brakerb** [comment]
Hey, we decided to stop accepting bug reports for develop because the code there changes fast and some people, that dont have the experience just pulled every newest update and spammed us with bugreports about stuff that would be fixed within hours anyway.

If you encounter a bug that is in develop for a longer period of time, feel free to report it. If the bug is new, wait about a week, usually cirical bugs a fixed within a few days.
