### ISSUE TITLE
TM2020 : Maplist menu in MatchSettings Manager causes script error

### ISSUE THREAD

**Issue by EmileCalixte** [EvoTM/EvoSC#61]
**Describe the bug**
A script error occurs when I try to browse Matchsettings maps.
https://i.imgur.com/f1esMnC.jpg

**Expected behavior**
No error

**To Reproduce**
1. As admin, open Matchsettings Manager
https://i.imgur.com/5s02xWZ.jpg

2. Select any maplist
https://i.imgur.com/8AExSSr.jpg

3. Clicks on 'Maps' tab
https://i.imgur.com/fE4hMcv.jpg

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.9.1.0

**When using git (please complete the following information):**
 - Current-Commit: c4ec61648c97b72f425cbfe6296bf803c9b2ed35

**Comment by Sil3ntStorm** [comment]
Also happening on 0.92.14 d2500183109ec9d0eeec97beb65efec779899d3d

**Comment by brakerb** [comment]
The MSM Maps-Tab is not yet optimized for TM2020

**Comment by EmileCalixte** [comment]
That's what I do atm. By the way, the automatic reload when we update the matchsettings file is a great feature !

**Comment by brakerb** [comment]
try now :) sorry for the late response but I was pretty busy

**Comment by EmileCalixte** [comment]
It works great ! 👍
