### ISSUE TITLE
TM2020 - EvoSC 0.92.14 : 101st checkpoint causes script error

### ISSUE THREAD

**Issue by EmileCalixte** [EvoTM/EvoSC#62]
This bug occurs only on the develop branch, anyway I think it could be interesting for you to have this report.

**Describe the bug**
When the cp-diffs plugin is enabled, a script error occurs when player passes the 101st checkpoint of a map.
https://i.imgur.com/1k03ux3.jpg

After the script error, the little widget above the race time seems to be stucked at '100', even when the player restarts map and even when map is skipped. The only solution is to disconnect and reconnect to the server, or run //resetall command.
https://i.imgur.com/J2zf6Ef.jpg

**Expected behavior**
No error

**To Reproduce**
1. Run a map having more than 100 checkpoints (edit: here is the map I've used https://trackmania.exchange/tracks/view/3190 )
2. Pass the 101st checkpoint
3. See error

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.92.14

**When using git (please complete the following information):**
 - Current-Commit: d2500183109ec9d0eeec97beb65efec779899d3d

**Comment by brakerb** [comment]
Hey, thanks for your report I'll look into it asap.

**Comment by brakerb** [comment]
I have increased the maximum number of CPs to 1000. 
I will probably replace it at some point to make it dynamic.

PS: The CPs at top now only show 2 rows while driving and scroll to the position of the local player
