### ISSUE TITLE
Server ranks not displayed

### ISSUE THREAD

**Issue by Nikolausman** [EvoTM/EvoSC#67]
Server ranks are not getting displayed
Also at the end of a match the "Top Ranks" is completely empty
Everyone has server rank 0 and it tells the following (even if i have a lot of locals):
![grafik](https://user-images.githubusercontent.com/28266051/88486652-86f1a100-cf7f-11ea-822f-c371c57f77fa.png)

**Expected behavior**
Server rank will be displayed

**To Reproduce**
1. Go to ranks.config.json ->  "enabled": true
2. Type /rank while being on server

**Screenshots/Logs**
![grafik](https://user-images.githubusercontent.com/28266051/88486876-2ebb9e80-cf81-11ea-8440-d1550138bb86.png)

 - EvoSC-Version: 0.92.22

**Comment by mantazzo** [comment]
Ranks are a bit broken at the moment it seems. There is the command
```
php esc fix:scores
```
which actually populated the ranks for me, but it was broken - shows rank 9999/0 for all players.

**Comment by Nikolausman** [comment]
> which actually populated the ranks for me, but it was broken - shows rank 9999/0 for all players.

Yeah it did the same for me now :/

**Comment by mantazzo** [comment]
After analyzing how this executes, and checking the mysql, seems like there's some sort of problem going on.
When you execute the command above, the code goes executing this (FixScores.php):
```
<...>
$playerIds = $evoSC->table('stats')->where('Locals', '>', 0)->pluck('Player')->toArray(); //line 57
<...>
```
After checking in with mysql DB, seems like it searches for any user which has Locals > 0 in the stats table (I assume that's local records counter), but seems like it actually doesn't populate - all users I found had 0 in there. That means Scores can't be calculated, and Ranks do, well, that outcome after executing the command.

**Comment by Nikolausman** [comment]
Can thus be fixed somehow?

**Comment by mantazzo** [comment]
Probably, but I'll leave this to the dev to find what's the issue there, as I'm a bit busy with other things now.

**Comment by Nikolausman** [comment]
Any news to fix the script?

**Comment by brakerb** [comment]
Sorry guys I was pretty busy lately, but I will look into it now

**Comment by brakerb** [comment]
It should be better now.

You can output data to the console with dump() or with dd() which dumps & dies

**Comment by mantazzo** [comment]
Tried the changes, which, unfortunately, didn't fix everything it seems. But I can at least see something in the log.

```
Hook->execute(): Exception: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'Rank = -1 WHERE 1=1' at line 1 (SQL: UPDATE stats SET Score = 0, Locals = 0, Rank = -1 WHERE 1=1;)
#0 C:\Users\manta\git\EvoSC-Dev\vendor\illuminate\database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('UPDATE stats SE...', Array, Object(Closure))
#1 C:\Users\manta\git\EvoSC-Dev\vendor\illuminate\database\Connection.php(459): Illuminate\Database\Connection->run('UPDATE stats SE...', Array, Object(Closure))
#2 C:\Users\manta\git\EvoSC-Dev\core\Classes\DB.php(26): Illuminate\Database\Connection->statement('UPDATE stats SE...')
#3 C:\Users\manta\git\EvoSC-Dev\core\Modules\Statistics\Statistics.php(123): EvoSC\Classes\DB::raw('UPDATE stats SE...')
#4 [internal function]: EvoSC\Modules\Statistics\Statistics::showScores(Object(Illuminate\Support\Collection))
#5 C:\Users\manta\git\EvoSC-Dev\core\Classes\Hook.php(79): call_user_func(Array, Object(Illuminate\Support\Collection))
#6 C:\Users\manta\git\EvoSC-Dev\core\Classes\Hook.php(164): EvoSC\Classes\Hook->execute(Object(Illuminate\Support\Collection))
#7 C:\Users\manta\git\EvoSC-Dev\core\Controllers\ModeScriptEventController.php(129): EvoSC\Classes\Hook::fire('ShowScores', Object(Illuminate\Support\Collection))
#8 C:\Users\manta\git\EvoSC-Dev\core\Controllers\ModeScriptEventController.php(52): EvoSC\Controllers\ModeScriptEventController::tmScores(Array)
#9 C:\Users\manta\git\EvoSC-Dev\core\Controllers\ModeScriptEventController.php(33): EvoSC\Controllers\ModeScriptEventController::call('Trackmania.Scor...', Array)
#10 C:\Users\manta\git\EvoSC-Dev\core\Controllers\EventController.php(82): EvoSC\Controllers\ModeScriptEventController::handleModeScriptCallbacks(Array)
#11 C:\Users\manta\git\EvoSC-Dev\core\Commands\EscRun.php(225): EvoSC\Controllers\EventController::handleCallbacks(Array)
#12 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Command\Command.php(255): EvoSC\Commands\EscRun->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Application.php(1000): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Application.php(271): Symfony\Component\Console\Application->doRunCommand(Object(EvoSC\Commands\EscRun), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#15 C:\Users\manta\git\EvoSC-Dev\vendor\symfony\console\Application.php(147): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 C:\Users\manta\git\EvoSC-Dev\esc(59): Symfony\Component\Console\Application->run()
#17 {main}
```

Commenting the line out (line 123) made the rankings work. Analyzing with VSCode shows the "Rank" text in different color than "Score" or "Locals", so maybe a small bug there.

**Comment by brakerb** [comment]
you're right. Rank is a reserved word in MySQL. I'll update it, please report if it works after

**Comment by mantazzo** [comment]
So far it seems to be working well after fixes.
