### ISSUE TITLE
Ranks not calculated properly

### ISSUE THREAD

**Issue by StevenKowalzik** [EvoTM/EvoSC#71]
**Describe the bug**
After a clean setup ranks are not calculated properly. No ranks were displayed first, even though local records on maps existed. After useing the esc fix:scores commands ranks for all players have been set to 9999. Even for people without local records yet.
The Stats Table shows 0 in the locales field, even though this player has local records.

**Expected behavior**
There should be enough data to calculate the ranks properly.

**To Reproduce**
1. Setup via Docker-Compose (https://github.com/barklebork/EvoSC-docker)
2. Removing Existing (Nadeo)-Maps and adding maps via TMX ID.
3. Driving a few records with 2 people.

**Screenshots/Logs**
```
+--------+--------+----------+----------+--------+---------+------+-----------+-------+------+------------+---------------------+
| Player | Visits | Playtime | Finishes | Locals | Ratings | Wins | Donations | Score | Rank | created_at | updated_at          |
+--------+--------+----------+----------+--------+---------+------+-----------+-------+------+------------+---------------------+
|      2 |      8 |    11655 |       55 |      0 |       0 |   22 |         0 |     0 | 9999 | NULL       | 2020-08-28 09:31:24 |
|      3 |      2 |       40 |        0 |      0 |       0 |    0 |         0 |     0 | 9999 | NULL       | 2020-08-26 18:28:19 |
|     33 |      3 |     3610 |        6 |      0 |       0 |    0 |         0 |     0 | 9999 | NULL       | 2020-08-27 20:10:59 |
|     34 |      1 |       40 |        0 |      0 |       0 |    0 |         0 |     0 | 9999 | NULL       | 2020-08-27 19:06:55 |
+--------+--------+----------+----------+--------+---------+------+-----------+-------+------+------------+---------------------+
```

**EvoSC (please complete the following information):**
EvoSC-Version 0.92.18

**Comment by brakerb** [comment]
I assume the docker image uses the master branch, I think I fixed it in develop. I'll merge develop into master.

**Comment by StevenKowalzik** [comment]
Update seems to have fixed it, thanks :) 👍
