### ISSUE TITLE
GameCrash when trying to open Profile via evoSC Scoreboard

### ISSUE THREAD

**Issue by wofnull** [EvoTM/EvoSC#76]
**Describe the bug**
Start game, join a server with evoSC ( tested on official EVO Servers and on mine aswell ) , type /scoreboard . open up the scoreboard ( evoSC scoreboard should overlay the normal one now )  press on view Profile on any player you want -> game Closes down without an error message, nothing happens

**Expected behavior**
Ingame there should be the possibility to view the Player Profile on the server, but it looks like even if this window opens up, it crashes the game client.

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.94.43

**Comment by brakerb** [comment]
Fixed in latest develop
