### ISSUE TITLE
Maps Info/Détails does not work TM²

### ISSUE THREAD

**Issue by KennyBz** [EvoTM/EvoSC#84]
**Describe the bug**
Maps Details does not work when clicked on it (top right), does not work in the / list either

**EvoSC (please complete the following information):**
 - EvoSC-Version Develop 0.95.17

**When using git (please complete the following information):**
 - Current-Commit: 67ac01a25fb2a6d2b08b90a9ffa794c60f8d6e71

**Comment by brakerb** [comment]
Fxied.
