### ISSUE TITLE
Adding mappacks doesn't work, gets error

### ISSUE THREAD

**Issue by martin-stralka** [EvoTM/EvoSC#85]
**Describe the bug**
In ManiaPlanet, when i try to add mappack the controller gives me an error and no maps are added.

```
An error occured calling EvoSC\Modules\MxDetails\MxDetails::showDetails: Client error: `GET https://api.mania.exchange/api/maps/get_map_info/multi/wiUfcShfNjgfIv49SsEKvvWqShm` resulted in a `404 Not Found` response:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xml (truncated...)
```

**Expected behavior**
It should add all of the maps, 

**To Reproduce**
Please explain what led to the issue.
1. Add mappack with //addpack command.
2. Click install.
3. Error

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.96.24
**When using git (please complete the following information):**
 - Current-Commit: 55d39649d9d4b6705b89b304affac0cecadadaf8

**Comment by brakerb** [comment]
Fixed. I recommend using the master branch, changed happen quickly on develop.
