### ISSUE TITLE
Informations about what for informations u get from server/us

### ISSUE THREAD

**Issue by BestNoob** [EvoTM/EvoSC#91]
I see that u recieve informations from the plugin and our servers ... 
Is it the whole setup and configuration ? What for infos do u collect ?

**Comment by brakerb** [comment]
We do not collect any information about you or your system, could you please tell me what made you think we do?

**Comment by BestNoob** [comment]
> 
> 
> We do not collect any information about you or your system, could you please tell me what made you think we do?

because one of you guys in discord told me a setting and path of my setup i never posted public ;D

**Comment by Chris92de** [comment]
If you're referring to my message stating "that's because your php-cli.ini error_reporting is set to E_ALL", well...
I've been programming in PHP for 13 years now and I know how to suppress warnings and certain default values in the PHP config.

**Comment by snixtho** [comment]
No one has gathered any information about your system, it's simply a logical deduction from technical knowledge and experience, and from how you explained your issue in Discord.

**Comment by ItsPhenom** [comment]
Also, if we ever implement things like telemetry, we will state it and also give the option to disable it.
