### ISSUE TITLE
/target does not display + or - on TM²

### ISSUE THREAD

**Issue by KennyBz** [EvoTM/EvoSC#92]
**Describe the bug**
When we do /target it displays the target but when we pass a cp it does not display the + or the - below.
And he does not update when we change map !

**Screenshots/Logs**
https://user-images.githubusercontent.com/15847867/101984100-9566fd80-3c7f-11eb-9b75-f5163b85012c.png

**EvoSC (please complete the following information):**
 - EvoSC-Version: 0.97.4

**Comment by brakerb** [comment]
fixed
