### ISSUE TITLE
Resource problem RAM raise up to 500MB per process

### ISSUE THREAD

**Issue by BestNoob** [EvoTM/EvoSC#95]
Hello guys,

i just recognized that the process RAM (TrackmaniaServer.exe) is raising up to 500MB while the other process running with PyPlanet/Uaseco are around 175MB - 250MB without players on it. Its lowering after shuttingdown EvoSC.

Server is running 4 days without a restart on Windows x64
EvoSC Version 0.96.31
TMServer Version 2020-12-10

**Comment by BestNoob** [comment]
* Sorry guys ;D
"Bug-Reports are only accepted for the master-branch"

**Comment by brakerb** [comment]
It is not a bug, thats why I removed the label.

**Comment by brakerb** [comment]
The reserved memory rises, with or without EvoSC running. Especially on map changes. Turning off EvoSC didnt not lower the memory usage of TrackmaniaServer.

EvoSC is a bit more demanding than UASECO, as it delivers a lot more dynamic features and runs 10x more cycler per second. Don't know about the architecture in PyPlanet, but afaik they are not as feature rich either.

We always try to optimize. A memory uasge of 200mb might be doable, or might not.

**Comment by BestNoob** [comment]
Hmm i recognized this now also with Uaseco & PyPlanet after using MX and MX ID requests like adding a map via MX ID or using MX Info via HUD

 ........ cheesus it raised up to 700MB why is there no limiter ? Its a very easy DDoS attack so xD just request MX ID or Dedimania stuff
