### ISSUE TITLE
Develop diverse errors Server Logfile

### ISSUE THREAD

**Issue by BestNoob** [EvoTM/EvoSC#96]
EvoSC Version: 0.97.9
TrackmaniaServer Version: 2020-12-18
Server System: Windows x64 PowerShell
PHP 7.4.13

Fresh Server Logfile with -vv

[evosc_2020-12-19.txt](https://github.com/EvoTM/EvoSC/files/5719472/evosc_2020-12-19.txt)

**Comment by BestNoob** [comment]
Should i post without labeling it xD ? Or maybe you add a Label for developer branch / general issues

**Comment by BestNoob** [comment]
EvoSC just paused/stopped working at ~14:00 than at ~16:11 i pressed ctrl + c in PowerShell windows and it goes further .....

What was this ? 
[evosc_2020-12-19_FULL.txt](https://github.com/EvoTM/EvoSC/files/5719623/evosc_2020-12-19_FULL.txt)

**Comment by brakerb** [comment]
The error in your log is just that your server couldnt connect to trackmania.exchange.

Do not run composer update as a user, it will mess up the package dependencies and might lead to bugs.

Also we only accept bug reports for the master branch, use develop at your own risk. You can keep track of pproblems and if they do not dissapear when merged with master, you can file a bug report.
