### ISSUE TITLE
Option to disable registering of local records during warmup

### ISSUE THREAD

**Issue by snixtho** [EvoTM/EvoSC#98]
**Describe the feature you'd like to see in EvoSC**
For example during the qualifications of a competition that uses the local records and have warmup on each map (mostly to let everyone be able to load the map in properly), it is annoying that local records are recorded during warmup when the times shouldnt count. Now obviously sometimes you also want the local records to record player's times, so having a configurable option for this can be a nice addition.

**Comment by brakerb** [comment]
New config values have been added for local records

```
  "ignore-warmup-times": false,
  "ignore-round-times": false,
  "ignore-time-attack-times": false
```
